#!/usr/bin/env python3
"""K06 — the YouTube adapter, against the REAL actor output. Step 16.

BUILD_GUIDE step 16 (K06); migration `030`; D37, D46.

The actor was run live on 2026-09-10 and its output read. Every fixture in
this file is shaped from that run, and the four things below are things the
run revealed that an assumed shape would have got wrong. That is the whole
argument of this suite: **the first guess at the input field was
`videoUrls` and it was wrong.**

1. **There is no flat transcript field, and the segments OVERLAP.**
   Segment 1 runs 0 → 2.16 and segment 2 STARTS at 1.04 — YouTube's
   rolling-caption format. Naive concatenation duplicates words throughout
   and the result looks like a rambling speaker rather than a joining bug.
2. **`isAutoGenerated` was true.** ASR, not a human transcript, and it has
   to stay traceable through to the derived knowledge.
3. **Identity is `videoId`.** The live input URL carried playlist and
   timestamp parameters; the canonical id does not.
4. **`channelId` is the creator**, not `channelName`.

WHAT THIS SUITE DOES NOT COVER: a video with no captions. That payload has
never been observed, so nothing here asserts its shape. What IS asserted is
the shape-independent invariant — no usable segments means no transcript,
`FULL_TEXT_NOT_AVAILABLE`, and nothing delivered.

The wire format is NOT verified: the transport is replaced, so the policy,
the request shape, the parsing, the de-overlap, the identity and the
provenance are proven and what Apify actually returns is not.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO / "testing"))

import psycopg

import acquisition as AQ
import youtube_apify as YT

FAILS: list[str] = []
PREFIX = "YTTEST_"

FIXTURES = REPO / "testing" / "fixtures" / "apify"

# The CAPTURED no-captions dataset (2026-09-11). Loaded rather than
# retyped: the whole value of this sample is that it is what the actor
# really returns, and a hand-copied version is a guess wearing its clothes.
NO_CAPTIONS = json.loads(
    (FIXTURES / "youtube_no_captions.json").read_text(encoding="utf-8"))

# The measured video. Real ids, real timings, real flags.
VIDEO_ID = "zg3GBH6fG2I"
CHANNEL_ID = "UCsQdi6X-12eUKBBBze46STA"
CHANNEL_NAME = "Glucose Revolution"

# The live input URL carried playlist and timestamp parameters. This is
# the seam: it is NOT the canonical identity.
MESSY_URL = (f"https://www.youtube.com/watch?v={VIDEO_ID}"
             "&list=PLsomething&t=142s&pp=iAQB")

# Real rolling-caption timings from the run: 0 -> 2.16, then 1.04 -> 3.52.
# Each caption redisplays the tail of the one before it.
OVERLAPPING = [
    {"text": "a glucose spike after",       "start": 0.00, "duration": 2.16, "end": 2.16},
    {"text": "after a meal is not",         "start": 1.04, "duration": 2.48, "end": 3.52},
    {"text": "is not the same as fasting",  "start": 2.40, "duration": 2.60, "end": 5.00},
    {"text": "as fasting glucose at all",   "start": 3.90, "duration": 2.30, "end": 6.20},
]
DEOVERLAPPED = "a glucose spike after a meal is not the same as fasting glucose at all"


def check(name: str, condition: bool, detail: str = "") -> None:
    if condition:
        print(f"  PASS  {name}")
    else:
        print(f"  FAIL  {name}  {detail}")
        FAILS.append(name)


def dataset_item(**over) -> dict:
    """One dataset item, with the field names the live run returned."""
    item = {
        "videoId": VIDEO_ID,
        "videoUrl": MESSY_URL,
        "videoTitle": f"{PREFIX}Why postprandial glucose matters",
        "channelName": CHANNEL_NAME,
        "channelId": CHANNEL_ID,
        "description": "A short explainer about glucose after meals.",
        "viewCount": 812345, "likeCount": 21000, "commentCount": 900,
        "subscriberCount": 1200000, "durationSeconds": 957,
        "keywords": ["glucose", "postprandial"],
        "thumbnail": "https://i.ytimg.com/vi/zg3GBH6fG2I/hq.jpg",
        "publishDate": "2025-04-11T09:00:00.000Z",
        "language": "en", "selectedLanguage": "en",
        "isAutoGenerated": True,
        "availableLanguages": ["en"],
        "segments": OVERLAPPING,
        "segmentCount": len(OVERLAPPING),
    }
    item.update(over)
    return item


class Wire:
    """The transport, recording the full call so the REQUEST can be asserted."""

    def __init__(self, items):
        self.items = items
        self.calls: list[dict] = []

    def __call__(self, url, headers, *, method="GET", body=None):
        self.calls.append({"url": url, "method": method, "body": body,
                           "headers": dict(headers)})
        payload = self.items(self.calls) if callable(self.items) else self.items
        return AQ.Response(200, {"Content-Type": "application/json"},
                           json.dumps(payload).encode("utf-8"))


def clear(conn) -> None:
    conn.execute("delete from source_envelopes where source_title like %s "
                 "   or external_ref = %s", (PREFIX + "%", VIDEO_ID))
    conn.execute("delete from source_items where title like %s or external_id = %s",
                 (PREFIX + "%", VIDEO_ID))
    for item in NO_CAPTIONS:
        conn.execute("delete from source_items where external_id = %s",
                     (item["videoId"],))
        conn.execute("delete from source_envelopes where external_ref = %s",
                     (item["videoId"],))
    conn.execute("delete from knowledge_sources where source_name like %s",
                 (PREFIX + "%",))
    conn.execute("delete from source_creators where external_id = %s", (CHANNEL_ID,))
    conn.execute("delete from source_fetches where url like %s", ("%apify%",))
    conn.execute("delete from source_queries where query_text like %s", ("videos:%",))


def make_source(conn, name: str) -> str:
    return str(conn.execute(
        """insert into knowledge_sources
             (source_name, source_type, source_roles, base_identifier,
              access_method, monitor_status)
           values (%s,'VIDEO_CHANNEL',ARRAY['DISCOVERY']::source_role[],%s,
                   'YOUTUBE',false)
           returning source_id""",
        (PREFIX + name, f"https://www.youtube.com/channel/{CHANNEL_ID}")
    ).fetchone()[0])


def source_row(conn, source_id):
    return conn.execute(
        "select source_id, source_name, source_type::text, base_identifier, "
        "       access_method, source_roles::text[] from knowledge_sources "
        " where source_id=%s", (source_id,)).fetchone()


def main() -> int:
    os.environ["LLM_API_KEY"] = ""
    os.environ["APIFY_TOKEN"] = "apify_api_TESTTOKEN_do_not_log_me"
    conn = psycopg.connect(os.environ["DATABASE_URL"], autocommit=True)
    clear(conn)

    root = Path(tempfile.mkdtemp(prefix="yt-"))
    os.environ["KNOWLEDGE_DIR"] = str(root)
    for name in ("inbox", "raw", "processed", "failed"):
        (root / name).mkdir(parents=True, exist_ok=True)
    import knowledge_ingest as KI     # after KNOWLEDGE_DIR: read at import
    import knowledge_discover as KD

    # ==================================================================
    print("\nthe rolling-caption overlap, on the run's real timings")

    naive = " ".join(s["text"] for s in OVERLAPPING)
    check("a naive join really does duplicate words — the bug is real",
          naive.split().count("after") == 2 and naive.split().count("fasting") == 2,
          naive)

    deduped = YT.dedupe_segments(OVERLAPPING)
    joined = " ".join(p["text"] for p in deduped if p["text"])
    check("de-overlapping reconstructs the sentence exactly once",
          joined == DEOVERLAPPED, joined)
    check("...and it is shorter than the naive join, not merely different",
          len(joined.split()) < len(naive.split()),
          f"{len(joined.split())} vs {len(naive.split())}")
    check("every dropped word is accounted for",
          sum(p["dropped_words"] for p in deduped)
          == len(naive.split()) - len(joined.split()),
          str([p["dropped_words"] for p in deduped]))

    # The fixture that can tell right from wrong (V2). A speaker who
    # genuinely repeats, with NO overlap in time, must survive intact --
    # a text-only de-duplicator would eat this.
    repeated = [
        {"text": "it is really really important", "start": 0.0, "end": 2.0},
        {"text": "really important", "start": 4.0, "end": 6.0},
    ]
    kept = " ".join(p["text"] for p in YT.dedupe_segments(repeated) if p["text"])
    check("a genuine repetition with no time overlap is NOT trimmed",
          kept == "it is really really important really important", kept)

    # Timing is the gate, so the same words WITH an overlap are trimmed.
    overlapping_repeat = [
        {"text": "it is really really important", "start": 0.0, "end": 4.5},
        {"text": "really important", "start": 3.0, "end": 6.0},
    ]
    trimmed = " ".join(p["text"] for p in YT.dedupe_segments(overlapping_repeat)
                       if p["text"])
    check("...and the identical words WITH a time overlap are",
          trimmed == "it is really really important", trimmed)

    # ==================================================================
    print("\nidentity is the videoId, never the URL it arrived on")

    check("the messy live URL resolves to the canonical id",
          YT.video_id_of(MESSY_URL) == VIDEO_ID, str(YT.video_id_of(MESSY_URL)))
    for form in (f"https://youtu.be/{VIDEO_ID}?t=90",
                 f"https://www.youtube.com/shorts/{VIDEO_ID}",
                 f"https://m.youtube.com/watch?v={VIDEO_ID}&list=X",
                 VIDEO_ID):
        check(f"...and so does {form[:44]}", YT.video_id_of(form) == VIDEO_ID)
    check("something that is not a video id is not invented into one",
          YT.video_id_of("https://www.youtube.com/@GlucoseRevolution") is None)
    check("the canonical URL carries no parameters",
          YT.canonical_url(VIDEO_ID) == f"https://www.youtube.com/watch?v={VIDEO_ID}")

    # ==================================================================
    print("\nthe request: POST, `urls`, and the token in a HEADER")

    source_id = make_source(conn, "channel")
    wire = Wire([dataset_item()])
    out = KD.discover_video(conn, source_row(conn, source_id),
                            transport=wire, urls=[MESSY_URL])
    check("one transcript is delivered to the inbox", out["delivered"] == 1, str(out))

    call = wire.calls[-1]
    body = json.loads(call["body"].decode("utf-8"))
    check("the actor is called with POST", call["method"] == "POST", call["method"])
    check("the input field is `urls` — the field the live run confirmed",
          "urls" in body, str(sorted(body)))
    check("...and NOT `videoUrls`, which was the wrong first guess",
          "videoUrls" not in body, str(sorted(body)))
    check("the canonical URL is what is sent, not the messy one",
          body["urls"] == [YT.canonical_url(VIDEO_ID)], str(body["urls"]))
    check("the token travels in an Authorization header",
          call["headers"].get("Authorization", "").startswith("Bearer "),
          str(sorted(call["headers"])))
    check("...and never in the URL", "token" not in call["url"], call["url"])

    logged = conn.execute(
        "select url from source_fetches where adapter='YOUTUBE' "
        " order by fetched_at desc limit 1").fetchone()[0]
    check("the permanent fetch record holds no credential",
          "TESTTOKEN" not in logged, logged)
    check("redact() would strip one that slipped into a query string anyway",
          "sekret" not in AQ.redact("https://api.apify.com/x?token=sekret&a=1")
          and "a=1" in AQ.redact("https://api.apify.com/x?token=sekret&a=1"),
          AQ.redact("https://api.apify.com/x?token=sekret&a=1"))

    # ==================================================================
    print("\none videoId is one item, however many URLs point at it")

    items_before = conn.execute(
        "select count(*) from source_items where external_id=%s",
        (VIDEO_ID,)).fetchone()[0]
    KD.discover_video(conn, source_row(conn, source_id), transport=Wire(
        [dataset_item(videoUrl=f"https://youtu.be/{VIDEO_ID}?t=300")]),
        urls=[f"https://youtu.be/{VIDEO_ID}?t=300"])
    items_after = conn.execute(
        "select count(*) from source_items where external_id=%s",
        (VIDEO_ID,)).fetchone()[0]
    check("a second entry point does not create a second row",
          items_before == 1 and items_after == 1,
          f"{items_before} -> {items_after}")

    # ==================================================================
    print("\nthe creator is the channelId, and a rename does not fork it")

    creators = conn.execute(
        "select creator_id, name, external_source from source_creators "
        " where external_id=%s", (CHANNEL_ID,)).fetchall()
    check("the creator is registered on the platform id", len(creators) == 1,
          str(creators))
    check("...qualified by its namespace", creators[0][2] == "YOUTUBE")

    KD.discover_video(conn, source_row(conn, source_id), transport=Wire(
        [dataset_item(channelName="Glucose Revolution (Official)")]),
        urls=[MESSY_URL])
    renamed = conn.execute(
        "select creator_id, name from source_creators where external_id=%s",
        (CHANNEL_ID,)).fetchall()
    check("a channel rename updates the SAME creator, it does not add one",
          len(renamed) == 1 and renamed[0][0] == creators[0][0],
          str(renamed))
    check("...and the new display name is taken",
          renamed[0][1] == "Glucose Revolution (Official)", str(renamed[0][1]))

    # ==================================================================
    print("\nthe CAPTURED no-captions sample: HTTP 200 and a healthy-looking item")

    captured = NO_CAPTIONS[0]
    captured_id = captured["videoId"]

    # The reason this sample matters: nothing about the response says
    # "failure" except four fields and a free-text error.
    check("the capture is a complete item, not an error response",
          captured["videoTitle"] and captured["channelId"]
          and captured["viewCount"] == 9213178
          and captured["durationSeconds"] == 515
          and len(captured["keywords"]) == 26, str(sorted(captured)[:6]))
    check("...and only the transcript fields are empty",
          captured["segments"] == [] and captured["segmentCount"] == 0
          and captured["language"] == "" and captured["selectedLanguage"] == ""
          and captured["availableLanguages"] == [], "fixture drifted")
    check("...carrying the actor's own error text",
          captured["error"] == "No transcript available for this video",
          str(captured.get("error")))

    try:
        YT.prepare(captured)
        check("the captured item is refused", False, "it produced a transcript")
    except YT.NoTranscript as exc:
        check("the captured item is refused", True)
        check("...and the refusal quotes the ACTOR's wording, not a generic one",
              "No transcript available for this video" in str(exc), str(exc)[:140])

    # isAutoGenerated is FALSE in this capture and that is NOT "a human
    # wrote it" -- it is false because there is no transcript at all.
    # Reading it without confirming segments records a failed fetch as the
    # highest-quality transcript type there is.
    check("the capture really does carry isAutoGenerated=false",
          captured["isAutoGenerated"] is False)
    check("...and reading it WITHOUT segments yields None, never False",
          YT.auto_generated_flag(captured, []) is None,
          str(YT.auto_generated_flag(captured, [])))
    check("...while a real transcript still reports its true flag",
          YT.auto_generated_flag(dataset_item(), YT.dedupe_segments(OVERLAPPING))
          is True)
    check("...and a human transcript is False, not None — the three are distinct",
          YT.auto_generated_flag(dataset_item(isAutoGenerated=False),
                                 YT.dedupe_segments(OVERLAPPING)) is False)

    # Keyed on `error` OR empty segments, never either alone: a future
    # actor version may drop one of the two signals.
    for label, item, expect in (
            ("an empty segments list with no error at all",
             dataset_item(videoId="a" * 11, segments=[], error=None), "no error"),
            ("an error alongside PRESENT segments",
             dataset_item(videoId="b" * 11, error="Transcript is partial"),
             "Transcript is partial"),
            ("no segments key whatsoever",
             dataset_item(videoId="c" * 11, segments=None, error=None),
             "no error"),
            ("segments that are all empty once de-overlapped",
             dataset_item(videoId="d" * 11, error=None,
                          segments=[{"text": "", "start": 0, "end": 1},
                                    {"text": "   ", "start": 1, "end": 2}]),
             "de-overlapped"),
    ):
        try:
            YT.prepare(item)
            check(f"{label} is refused", False, "it produced a transcript")
        except YT.NoTranscript as exc:
            check(f"{label} is refused", expect.lower() in str(exc).lower(),
                  str(exc)[:140])

    # ------------------------------------------------------------------
    # End to end on the captured payload, through the real adapter.
    before = len(list((root / "inbox").glob("*")))
    empty_out = KD.discover_video(
        conn, source_row(conn, source_id), transport=Wire(NO_CAPTIONS),
        urls=[YT.canonical_url(captured_id)])
    after = len(list((root / "inbox").glob("*")))

    check("nothing at all reaches the inbox — not even a sidecar",
          empty_out["delivered"] == 0 and empty_out["unavailable"] == 1
          and before == after, f"{before} -> {after}, {empty_out}")
    status = conn.execute(
        "select ingestion_status::text, access_note from source_items "
        " where external_id=%s", (captured_id,)).fetchone()
    check("the item IS registered, so it is not rediscovered next run",
          status is not None, "no row")
    check("...as FULL_TEXT_NOT_AVAILABLE",
          status[0] == "FULL_TEXT_NOT_AVAILABLE", str(status[0]))
    check("...with the actor's own error text in the note",
          "No transcript available for this video" in (status[1] or ""),
          str(status[1])[:140])

    # No transcript means no envelope: an empty body must never become a
    # source, and the strongest proof is that nothing downstream exists.
    envelopes = conn.execute(
        "select count(*) from source_envelopes where external_ref=%s",
        (captured_id,)).fetchone()[0]
    check("no envelope was opened for a video with no transcript",
          envelopes == 0, str(envelopes))
    asr_claim = conn.execute(
        """select count(*) from source_envelopes
            where external_ref=%s and transcript_is_auto_generated is not null""",
        (captured_id,)).fetchone()[0]
    check("...so nothing recorded it as a human transcript", asr_claim == 0)

    # Re-running must not duplicate the row or move it backwards.
    KD.discover_video(conn, source_row(conn, source_id),
                      transport=Wire(NO_CAPTIONS),
                      urls=[YT.canonical_url(captured_id)])
    again = conn.execute(
        "select count(*), min(ingestion_status::text) from source_items "
        " where external_id=%s", (captured_id,)).fetchone()
    check("a second run neither duplicates it nor changes its status",
          again[0] == 1 and again[1] == "FULL_TEXT_NOT_AVAILABLE", str(again))

    # ==================================================================
    print("\na batch is ONE actor run — the start fee dominates a single video")

    batch_wire = Wire(lambda calls: [
        dataset_item(videoId="e" * 11, segments=OVERLAPPING),
        dataset_item(videoId="f" * 11, segments=OVERLAPPING)])
    batch = KD.discover_video(
        conn, source_row(conn, source_id), transport=batch_wire,
        urls=[f"https://www.youtube.com/watch?v={'e' * 11}",
              f"https://www.youtube.com/watch?v={'f' * 11}"])
    posts = [c for c in batch_wire.calls if c["method"] == "POST"]
    check("two videos cost one run, not two", len(posts) == 1 and
          batch["delivered"] == 2, f"{len(posts)} run(s), {batch['delivered']}")
    check("...and both URLs went in the one request",
          len(json.loads(posts[0]["body"])["urls"]) == 2)

    # ==================================================================
    print("\nclearing the authorization returns the adapter to refusing")

    note = conn.execute("select authorization_note from acquisition_adapters "
                        " where adapter='YOUTUBE'").fetchone()[0]
    check("an authorization IS recorded now", bool((note or "").strip()))
    check("...and it says the authorization is with Apify, not from YouTube",
          "apify" in (note or "").lower() and "not a permission from youtube"
          in (note or "").lower(), (note or "")[:120])

    silent = Wire([dataset_item()])
    try:
        with conn.transaction():
            conn.execute("update acquisition_adapters set authorization_note=null "
                         " where adapter='YOUTUBE'")
            # The refusal is CAUGHT and turned into ACCESS_DENIED -- a true
            # statement about our access, which is the K06 posture. It is
            # not an exception for the caller to handle.
            denied = KD.discover_video(conn, source_row(conn, source_id),
                                       transport=silent, urls=[MESSY_URL])
            check("with the note cleared the adapter delivers nothing",
                  denied["delivered"] == 0, str(denied))
            check("...and NOTHING was requested — not even robots.txt",
                  silent.calls == [], str(len(silent.calls)))
            item_status = conn.execute(
                "select ingestion_status::text, access_note from source_items "
                " where item_id=%s", (denied["item_id"],)).fetchone()
            check("...the item is ACCESS_DENIED, not FAILED",
                  item_status[0] == "ACCESS_DENIED", str(item_status[0]))
            check("...saying no authorization is recorded",
                  "authorization" in (item_status[1] or "").lower(),
                  str(item_status[1])[:100])
            raise RuntimeError("rollback")
    except RuntimeError:
        pass
    check("the authorization note survives the rollback",
          conn.execute("select authorization_note from acquisition_adapters "
                       " where adapter='YOUTUBE'").fetchone()[0] == note)

    # The token is the other half of the authorization, and its absence is
    # the same finding — not a configuration crash that takes the run down.
    tokenless = Wire([dataset_item()])
    saved = os.environ.pop("APIFY_TOKEN")
    try:
        out_notoken = KD.discover_video(conn, source_row(conn, source_id),
                                        transport=tokenless, urls=[MESSY_URL])
        check("no APIFY_TOKEN is an access finding, not a crash",
              out_notoken["delivered"] == 0, str(out_notoken))
        check("...nothing was requested without a credential",
              tokenless.calls == [], str(len(tokenless.calls)))
        check("...and the refusal is RECORDED, not silent",
              conn.execute(
                  "select count(*) from source_fetches where adapter='YOUTUBE' "
                  "  and outcome='REFUSED_NO_CREDENTIAL'").fetchone()[0] == 1)
    finally:
        os.environ["APIFY_TOKEN"] = saved

    hosts = conn.execute("select allowed_hosts, respect_robots from "
                         " acquisition_adapters where adapter='YOUTUBE'").fetchone()
    check("the adapter may only reach api.apify.com",
          hosts[0] == ["api.apify.com"], str(hosts[0]))
    try:
        AQ.fetch(conn, "YOUTUBE", "https://www.youtube.com/watch?v=x",
                 transport=Wire([]))
        check("...so youtube.com itself is refused", False, "it fetched")
    except AQ.Refused as exc:
        check("...so youtube.com itself is refused",
              "allowed_hosts" in str(exc) or "may only fetch" in str(exc),
              str(exc)[:100])

    # ==================================================================
    print("\nthe timestamp survives into the chunks, and ASR stays visible")

    delivered = sorted((root / "inbox").glob(f"{VIDEO_ID}*.md"))
    check("the transcript is in the inbox as markdown", len(delivered) >= 1,
          str([p.name for p in delivered]))
    text = delivered[0].read_text(encoding="utf-8")
    check("its block headings are timestamps", "\n## [00:00]" in text, text[:200])
    check("the description is present under its own heading, not merged in",
          "## Video description" in text)
    check("the transcript text is the de-overlapped one",
          DEOVERLAPPED in text, text[-200:])

    receipt = KI.ingest_one(conn, delivered[0])
    check("it normalizes through the ordinary inbox path (D37)",
          receipt.outcome == "NORMALIZED", receipt.detail or "")

    env = conn.execute(
        "select transcript_is_auto_generated, transcript_provider, "
        "       transcript_language, external_ref, creator_id "
        "  from source_envelopes where envelope_id=%s",
        (receipt.envelope_id,)).fetchone()
    check("the envelope records that this is ASR", env[0] is True, str(env))
    check("...and who produced it", (env[1] or "").startswith("apify:"), str(env[1]))
    check("...and in what language", env[2] == "en", str(env[2]))
    check("...and the canonical id, not the URL it came in on",
          env[3] == VIDEO_ID, str(env[3]))
    check("...and the creator it belongs to", env[4] is not None)

    locations = [r[0] for r in conn.execute(
        """select c.metadata->>'location' from knowledge_chunks c
             join source_documents d on d.document_id = c.document_id
             join source_items i on i.item_id = d.item_id
            where i.external_id = %s order by c.chunk_index""",
        (VIDEO_ID,)).fetchall()]
    check("a chunk's location carries the minute it came from",
          any("[00:00]" in (loc or "") for loc in locations), str(locations))
    check("...and the description chunk is located as the description",
          any("Video description" in (loc or "") for loc in locations),
          str(locations))
    asr_flags = {r[0] for r in conn.execute(
        """select c.metadata->>'auto_generated' from knowledge_chunks c
             join source_documents d on d.document_id = c.document_id
             join source_items i on i.item_id = d.item_id
            where i.external_id = %s""", (VIDEO_ID,)).fetchall()}
    check("every chunk of an ASR transcript is marked as one",
          asr_flags == {"true"}, str(asr_flags))

    # A claim from this source must be traceable to the machine
    # transcription it rests on. `postprandial`, `glycaemic` and `visceral
    # adiposity` are exactly what ASR mangles, which is why the flag has to
    # reach this far.
    #
    # Driven through the REAL K09 (V2): the provenance edge this depends on
    # is written by `knowledge_extract`, and a hand-inserted claim would
    # prove the view's SQL against a row the production path never makes.
    import knowledge_extract as KX
    envelope = conn.execute(
        "select envelope_id, source_title, source_kind, source_role::text, "
        "       rights::text, content_hash, source_version "
        "  from source_envelopes where envelope_id=%s",
        (receipt.envelope_id,)).fetchone()
    extracted = KX.extract_one(conn, envelope)
    check("K09 extracts from the transcript", extracted["outcome"] == "EXTRACTED"
          and extracted["claims"] >= 1, str(extracted))

    traced = conn.execute(
        "select transcript_provider, creator_external_id, transcript_language "
        "  from v_asr_derived_claims "
        " where envelope_id=%s", (receipt.envelope_id,)).fetchall()
    check("every claim from an ASR transcript is listed as ASR-derived",
          len(traced) == extracted["claims"], f"{len(traced)} of {extracted['claims']}")
    check("...with the provider that produced the transcription",
          traced and (traced[0][0] or "").startswith("apify:"), str(traced[:1]))
    check("...alongside the creator's stable id",
          traced and traced[0][1] == CHANNEL_ID, str(traced[:1]))

    # The counterfactual: a source that is NOT a transcript must not appear
    # here. Without this the view could be selecting everything.
    plain = conn.execute(
        "select count(*) from v_asr_derived_claims v "
        "  join source_envelopes e on e.envelope_id = v.envelope_id "
        " where e.transcript_is_auto_generated is not true").fetchone()[0]
    check("a source that is not an ASR transcript is not listed", plain == 0,
          str(plain))
    clear(conn)
    print()
    if FAILS:
        print(f"FAILED: {len(FAILS)}")
        for f in FAILS:
            print(f"  - {f}")
        return 1
    print("test_youtube: all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
