-- =====================================================================
-- 030_youtube_transcripts.sql   K06 — the YOUTUBE adapter, against real output
--
-- Migration `021` registered YOUTUBE as `requires_authorization` with NO
-- authorization note, so the chokepoint refused every fetch and every item
-- became ACCESS_DENIED. That was correct while no authorization existed.
--
-- One now does, and it is worth stating precisely what it is: the
-- practitioner holds an **Apify** account, and the transcript comes from a
-- published actor on that platform under Apify's terms. This is an
-- authorization to call Apify's documented API with our token. It is NOT
-- an authorization from YouTube, and nothing here reads youtube.com.
-- `allowed_hosts` says so structurally.
--
-- Everything else in this migration exists because the actor was RUN and
-- its real output read, rather than assumed. Four things the real payload
-- showed that a guessed shape would have missed are recorded in D46; two
-- of them need schema.
-- =====================================================================


-- ---------------------------------------------------------------------
-- A. The authorization, recorded where the chokepoint reads it
-- ---------------------------------------------------------------------

UPDATE acquisition_adapters
   SET requires_authorization = true,
       authorization_note =
         'Apify account held by the practitioner; transcripts come from the '
         'published actor automation-lab/youtube-transcript over Apify''s '
         'documented API, authenticated with APIFY_TOKEN. The authorization '
         'is WITH APIFY and is not a permission from YouTube: nothing here '
         'requests youtube.com, which is why allowed_hosts is api.apify.com '
         'alone. Revoking the token or clearing this note returns the '
         'adapter to refusing, and the item to ACCESS_DENIED.',
       allowed_hosts = ARRAY['api.apify.com'],
       -- A documented API called with our own credential. robots.txt
       -- governs crawling a site's pages and does not apply, the same
       -- reasoning as PUBMED -- and this is the ONLY reason it is off.
       respect_robots = false,
       min_interval_seconds = 2,
       repeat_after_hours = 24,
       notes =
         'K06. Measured on a real run 2026-09-10: one video cost $0.01 '
         'because the per-run start fee dominates a single-video run. '
         'BATCH — the actor takes a list on its `urls` input, and the '
         'advertised per-video rate is only approached across a batch. '
         'The input field is `urls`, confirmed live; `videoUrls` was a '
         'wrong guess and is what testing instead of assuming caught.'
 WHERE adapter = 'YOUTUBE';


-- ---------------------------------------------------------------------
-- B. An auto-generated transcript is ASR, and must stay traceable as one
-- ---------------------------------------------------------------------
--
-- The live run returned `isAutoGenerated: true`. That is machine speech
-- recognition, not a human transcript, and the terms it mangles are
-- exactly this library's vocabulary -- "postprandial", "glycaemic",
-- "visceral adiposity". A concept proposed from an ASR transcript is not
-- wrong, but a reviewer has to be able to SEE that it came from one.
--
-- These columns are on the envelope because that is where a fact about
-- how the source was obtained belongs, and NULL means "not a transcript"
-- rather than "human" -- the distinction `never_assessed` makes elsewhere.
-- ---------------------------------------------------------------------

ALTER TABLE source_envelopes
    ADD COLUMN IF NOT EXISTS transcript_is_auto_generated boolean,
    ADD COLUMN IF NOT EXISTS transcript_language          text,
    ADD COLUMN IF NOT EXISTS transcript_provider          text,
    -- The canonical id of the thing itself, independent of the URL it
    -- happened to be found through. See section C.
    ADD COLUMN IF NOT EXISTS external_ref                 text;

COMMENT ON COLUMN source_envelopes.transcript_is_auto_generated IS
'TRUE for machine speech recognition, FALSE for a human transcript, NULL for a source that is not a transcript at all. NULL is not "human": a source nobody recorded this for has not been assessed.';

ALTER TABLE source_envelopes
    ADD CONSTRAINT ck_transcript_provenance_complete CHECK (
        transcript_is_auto_generated IS NULL
        OR transcript_provider IS NOT NULL);

COMMENT ON CONSTRAINT ck_transcript_provenance_complete ON source_envelopes IS
'Claiming a transcript is or is not auto-generated requires saying who produced it. "Auto-generated by something" cannot be checked later, and the check is the entire point of recording it.';

CREATE INDEX IF NOT EXISTS idx_envelope_external_ref
    ON source_envelopes (external_ref) WHERE external_ref IS NOT NULL;


-- ---------------------------------------------------------------------
-- C. Identity is the CANONICAL ID, never the URL it arrived on
-- ---------------------------------------------------------------------
--
-- The URL used for the live run carried playlist and timestamp
-- parameters; the videoId does not. Two entry points to one video would
-- otherwise be two `source_items` rows -- the same seam that has already
-- produced a duplicate in this layer once.
--
-- The adapter canonicalises before it registers anything, so `uq_item_url`
-- does most of the work. This index is what makes it structural: within
-- one source, an external id appears once.
--
-- Scoped to (source_id, external_id) rather than external_id alone
-- because `external_id` also holds FEED GUIDs (K04/K05), which are unique
-- per feed and carry no promise of being unique across feeds. A global
-- index would refuse a legitimate second feed.
-- ---------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS uq_item_source_external
    ON source_items (source_id, external_id)
    WHERE external_id IS NOT NULL AND source_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- D. A creator is a stable ID, not a display name
-- ---------------------------------------------------------------------
--
-- `channelName` can change; `channelId` does not. §40 creator profiles
-- accumulate across sources, and keying them on a name means a rename
-- silently starts a second profile with none of the first one's history.
-- ---------------------------------------------------------------------

ALTER TABLE source_creators
    ADD COLUMN IF NOT EXISTS external_id  text,
    ADD COLUMN IF NOT EXISTS external_source text;

COMMENT ON COLUMN source_creators.external_id IS
'The platform''s stable identity for this creator (a YouTube channelId, for example). Display names change; this does not. Matching on the name instead is how one creator becomes two profiles, each with half the history.';

ALTER TABLE source_creators
    ADD CONSTRAINT ck_creator_external_qualified CHECK (
        external_id IS NULL OR external_source IS NOT NULL);

COMMENT ON CONSTRAINT ck_creator_external_qualified ON source_creators IS
'An external id is only an identity within a namespace. A bare id with no platform is a string that happens to look unique.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_creator_external
    ON source_creators (external_source, external_id)
    WHERE external_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- E. Traceability (needs source_creators.external_id from D above)
-- ---------------------------------------------------------------------

-- Traceability, as a query rather than a convention. "Which derived
-- knowledge rests on machine transcription?" has an answer.
CREATE OR REPLACE VIEW v_asr_derived_claims
WITH (security_invoker = true) AS
SELECT cl.claim_id,
       cl.claim_text,
       cl.claim_type,
       cl.extraction_confidence,
       e.envelope_id,
       e.source_title,
       e.source_url,
       e.transcript_provider,
       e.transcript_language,
       e.transcript_is_auto_generated,
       cr.name        AS creator_name,
       cr.external_id AS creator_external_id
  FROM claims cl
  -- The provenance registry, not a join invented for this view. Hard rule
  -- 12: every derived object registers in `knowledge_entities` and
  -- `envelope_derived_records` carries the edge. Joining claims to
  -- envelopes through `source_items.source_id` instead would look right
  -- and be wrong -- the envelope's source is the one the NORMALIZER
  -- upserts for the document, not the channel the item was discovered
  -- from, so that join silently returns nothing.
  JOIN envelope_derived_records edr
    ON edr.derived_id = cl.claim_id AND edr.derived_kind = 'CLAIM'
  JOIN source_envelopes e ON e.envelope_id = edr.envelope_id
  LEFT JOIN source_creators cr ON cr.creator_id = e.creator_id
 WHERE e.transcript_is_auto_generated;

COMMENT ON VIEW v_asr_derived_claims IS
'Claims that rest on machine speech recognition. ASR mangles exactly the terms this library cares about, so a reviewer must be able to ask which conclusions came from one — and get a list, not a guess.';

GRANT SELECT ON v_asr_derived_claims TO phi_runtime, phi_practitioner;
