#!/usr/bin/env python3
"""Regenerate prompts/MANIFEST.json from the prompt files.

Every field it writes is REPRODUCIBLE from the file, and
test_prompt_contracts.py asserts all of them for all seven prompts.

Why that is worth saying: the manifest used to carry `sections_expected`,
a hand-declared number whose counting rule could not be reproduced. No rule
matched all seven prompts and the closest matched four. It looked like
coverage and was not -- and its Engine 7 `sha256` had been stale since the
D16 merge without anything noticing, which is what a field nobody checks
does.

Run this after editing a prompt, then run the suites.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROMPTS = REPO / "prompts"

# A numbered top-level section: "## 12." or "## 63A.". Sub-headings and
# unnumbered headings ("## R8.", "## Addendum A") are deliberately not
# counted -- Engine 7's Parts II/III use R-numbers, so its section count is
# lower than its heading count and that is correct rather than a miscount.
SECTION_RULE = r"^## \d+[A-Z]?\."

HANDOFF_OPEN = r"^<[A-Z][A-Z0-9_]*_(HANDOFF|DELTA)>$"
HANDOFF_CLOSE = r"^</[A-Z][A-Z0-9_]*_(HANDOFF|DELTA)>$"


def entry(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    return {
        "file": path.name,
        "words": len(text.split()),
        "chars": len(text),
        "sections": len(re.findall(SECTION_RULE, text, re.M)),
        # A tag that appears only inside a heading is not emittable: a model
        # following the field template literally would produce a block the
        # runtime cannot find. That is a real defect this catches (D24b).
        "has_control_tag": "<CONTROL_BLOCK>" in text,
        "has_handoff_open_tag": bool(re.search(HANDOFF_OPEN, text, re.M)),
        "has_handoff_close_tag": bool(re.search(HANDOFF_CLOSE, text, re.M)),
        "sha256": hashlib.sha256(text.encode()).hexdigest(),
    }


def build() -> list[dict]:
    header = {
        "_note": (
            "Generated by scripts/manifest.py. Every field is REPRODUCIBLE "
            "from the file and asserted by test_prompt_contracts.py for all "
            "seven prompts."),
        "_section_rule": SECTION_RULE,
        "_section_rule_meaning": (
            "A numbered top-level section heading: '## 12.' or '## 63A.'. "
            "Unnumbered headings such as '## R8.' or '## Addendum A' are not "
            "counted, which is why Engine 7's count is lower than its total "
            "heading count."),
    }
    return [header] + [entry(p) for p in sorted(PROMPTS.glob("engine*.md"))]


def main() -> int:
    current = json.loads((PROMPTS / "MANIFEST.json").read_text())
    fresh = build()
    if "--check" in sys.argv:
        if current != fresh:
            print("MANIFEST.json is stale. Run: python3 scripts/manifest.py",
                  file=sys.stderr)
            return 1
        print(f"MANIFEST.json matches all {len(fresh) - 1} prompts.")
        return 0
    (PROMPTS / "MANIFEST.json").write_text(json.dumps(fresh, indent=2) + "\n")
    for row in fresh[1:]:
        print(f"  {row['file']:34s} {row['sections']:>3d} sections  "
              f"{row['chars']:>7,} chars  {row['sha256'][:12]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
