#!/usr/bin/env python3
"""K06 — YouTube transcripts, via the Apify actor, shaped by its REAL output.

BUILD_GUIDE step 16 (K06); migration `030`; D37, D46. Engine 7 §12, §16,
§40, §42, §47, §52.

    python3 scripts/youtube_apify.py --url https://www.youtube.com/watch?v=…

### This module makes no request of its own

Everything goes through `acquisition.fetch()` (D37). The chokepoint gained
`method`, `body` and `extra_headers` for this, rather than this file
gaining its own `urlopen` — an adapter that reaches around the chokepoint
is an access path with no policy on it, and the policy is the only thing
standing between "a registered source" and "scraping".

### The input field is `urls`

Confirmed on a live run 2026-09-10. The first guess was `videoUrls` and it
was **wrong**, which is the entire argument for running the thing before
writing code against it.

**One detail is still assumed**: whether each element of `urls` is a plain
string or an object. `INPUT_ITEMS_AS_OBJECTS` below is where that lives, so
there is exactly one line to change and it is the first place to look if a
live batch comes back empty.

### What the real output actually contains

    videoId, videoUrl, videoTitle, channelName, channelId, description,
    viewCount, likeCount, commentCount, subscriberCount, durationSeconds,
    keywords, thumbnail, publishDate, language, selectedLanguage,
    isAutoGenerated, availableLanguages, segments, segmentCount

Four things the live output showed that an assumed shape would not have:

1. **There is no flat transcript field.** Only `segments` — and the
   segments OVERLAP. In the measured video, segment 1 runs 0 → 2.16 and
   segment 2 STARTS at 1.04. That is YouTube's rolling-caption format:
   each caption redisplays the tail of the one before it. Naive
   concatenation duplicates words throughout, and the damage does not look
   like a joining bug downstream — it looks like a rambling source, so
   claim extraction blames the speaker. `dedupe_segments()` below is the
   fix, and it uses the TIMINGS to decide when to look for an overlap
   rather than guessing from the text.
2. **`isAutoGenerated` was true.** That is ASR, not a human transcript,
   and it travels on the envelope (migration `030`). "Postprandial",
   "glycaemic" and "visceral adiposity" are exactly what ASR mangles, so a
   concept proposed from one has to stay traceable to it.
3. **Identity is `videoId`, never `videoUrl`.** The URL used for the live
   run carried playlist and timestamp parameters and the id does not. Two
   entry points to one video would be two rows.
4. **`channelId` is the creator, not `channelName`.** Names change; §40
   profiles accumulate across sources, and keying on a name means a rename
   starts a second profile holding half the history.

### Timings survive to the derived knowledge, using the normalizer we have

The transcript is rendered as markdown whose block headings ARE timestamps
— `## [14:32]`. `knowledge_ingest.segment()` already treats a heading path
as the chunk's `location` (§16, §42: "chapter, page and timestamp are part
of the content"), K09 already carries `location` onto the claim. So a
claim citing minute 14 is provenance with **no second ingestion path and
no change to the normalizer's chunking** (D37).

### Cost

Measured, not estimated: one video, **$0.01**, because the per-run start
fee dominates a single-video run. The advertised per-video rate is only
approached across a batch — so `fetch_transcripts()` takes a LIST.

### The no-captions case is NOT implemented from a guess

A video without captions has never been run, so its payload shape is
unknown and nothing here pretends otherwise. What IS enforced is the
shape-independent invariant: **no usable segments means no transcript**,
the item is `FULL_TEXT_NOT_AVAILABLE`, and nothing is delivered. An empty
string must never travel as a transcript — it would pass through
extraction as a source that taught us nothing, and §54's delta analysis
would agree with it.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from urllib.parse import parse_qs, urlparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import acquisition as AQ  # noqa: E402

ADAPTER = "YOUTUBE"
ACTOR_ID = "automation-lab~youtube-transcript"
RUN_URL = ("https://api.apify.com/v2/acts/{actor}"
           "/run-sync-get-dataset-items?clean=true&format=json")

# Confirmed live. `videoUrls` was the wrong guess.
INPUT_FIELD = "urls"
# The ONE unconfirmed detail — see the module docstring.
INPUT_ITEMS_AS_OBJECTS = False

PROVIDER = f"apify:{ACTOR_ID}"

# A YouTube video id: 11 characters of the URL-safe alphabet.
VIDEO_ID = re.compile(r"^[A-Za-z0-9_-]{11}$")

# How much transcript goes under one timestamp heading. Comfortably under
# knowledge_ingest.TARGET_CHARS so a block is not split across chunks --
# a split block would put half the text under a timestamp it did not
# belong to, which is worse than no timestamp.
BLOCK_CHARS = 1200

# Floating-point caption timings do not need a tolerance this large to be
# equal; it exists so a 1ms rounding artefact is not read as an overlap.
TIME_EPSILON = 0.01

WORD_PUNCT = re.compile(r"[^\w']+", re.UNICODE)


class ApifyUnavailable(RuntimeError):
    """No token, or the run returned something that is not a dataset."""


class NoTranscript(RuntimeError):
    """The item has no usable segments. A true statement, not a failure."""


# ---------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------

def video_id_of(url: str) -> str | None:
    """The canonical id from any of the URL forms YouTube uses.

    Playlist and timestamp parameters are noise on the identity and are
    exactly what made one video look like two.
    """
    if not url:
        return None
    if VIDEO_ID.match(url.strip()):
        return url.strip()
    parts = urlparse(url.strip())
    host = (parts.hostname or "").lower().removeprefix("www.")
    if host in ("youtu.be",):
        candidate = parts.path.lstrip("/").split("/")[0]
        return candidate if VIDEO_ID.match(candidate) else None
    if host.endswith("youtube.com"):
        query = parse_qs(parts.query)
        if query.get("v"):
            candidate = query["v"][0]
            return candidate if VIDEO_ID.match(candidate) else None
        segments = [p for p in parts.path.split("/") if p]
        if len(segments) >= 2 and segments[0] in ("shorts", "embed", "live", "v"):
            return segments[1] if VIDEO_ID.match(segments[1]) else None
    return None


def canonical_url(video_id: str) -> str:
    return f"https://www.youtube.com/watch?v={video_id}"


def channel_url(channel_id: str) -> str:
    return f"https://www.youtube.com/channel/{channel_id}"


# ---------------------------------------------------------------------
# The rolling-caption overlap
# ---------------------------------------------------------------------

def _number(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _key(words: list[str]) -> list[str]:
    """Compare on words, not on characters, ignoring case and punctuation.

    A caption redisplayed by the player can differ in trailing punctuation
    from the same words in the segment before it.
    """
    return [WORD_PUNCT.sub("", w).lower() for w in words]


def segment_end(seg: dict) -> float | None:
    end = _number(seg.get("end"))
    if end is not None:
        return end
    start, duration = _number(seg.get("start")), _number(seg.get("duration"))
    return None if start is None or duration is None else start + duration


def dedupe_segments(segments: list[dict]) -> list[dict]:
    """De-overlap YouTube's rolling captions.

    Each caption redisplays the tail of the previous one, so segment n and
    segment n+1 share words AND share time. The TIMING is what gates the
    trim: two segments that do not overlap in time are two different things
    being said, and a speaker repeating themselves must survive intact.

    Returns one entry per input segment, in order, each carrying what it
    contributed and how much was dropped. Nothing is discarded silently --
    `dropped_words` is what makes the de-overlap auditable.
    """
    out: list[dict] = []
    prev_words: list[str] = []
    prev_end: float | None = None

    for seg in segments:
        raw = (seg.get("text") or "").strip()
        words = raw.split()
        start = _number(seg.get("start"))
        end = segment_end(seg)

        drop = 0
        overlapped = (prev_end is not None and start is not None
                      and start < prev_end - TIME_EPSILON)
        if overlapped and prev_words and words:
            previous, current = _key(prev_words), _key(words)
            for k in range(min(len(previous), len(current)), 0, -1):
                if previous[-k:] == current[:k]:
                    drop = k
                    break

        out.append({"start": start, "end": end,
                    "text": " ".join(words[drop:]),
                    "dropped_words": drop,
                    "time_overlap": overlapped})
        prev_words = words
        prev_end = end if end is not None else prev_end
    return out


def timestamp(seconds: float | None) -> str:
    if seconds is None:
        return "??:??"
    total = int(seconds)
    hours, rest = divmod(total, 3600)
    minutes, secs = divmod(rest, 60)
    return (f"{hours}:{minutes:02d}:{secs:02d}" if hours
            else f"{minutes:02d}:{secs:02d}")


def blocks(deduped: list[dict], limit: int = BLOCK_CHARS) -> list[dict]:
    """Group contributions into timestamped blocks of retrieval size."""
    out: list[dict] = []
    current: list[str] = []
    start: float | None = None
    size = 0
    for piece in deduped:
        if not piece["text"]:
            continue
        if start is None:
            start = piece["start"]
        if size and size + len(piece["text"]) > limit:
            out.append({"start": start, "text": " ".join(current)})
            current, size, start = [], 0, piece["start"]
        current.append(piece["text"])
        size += len(piece["text"]) + 1
    if current:
        out.append({"start": start, "text": " ".join(current)})
    return out


# ---------------------------------------------------------------------
# The document handed to the inbox
# ---------------------------------------------------------------------

def transcript_markdown(video: dict, deduped: list[dict]) -> str:
    """Markdown whose block headings are timestamps.

    The H1 is the title, so `segment()` produces locations of the form
    `Title > [14:32]` and every chunk carries the minute it came from.
    The description gets its OWN heading rather than being dropped or
    merged: it is genuinely part of the source (§12 — what a creator says
    about their own material is a fact about the creator), and a claim
    drawn from promotional copy must be distinguishable from one made on
    camera. The location is what distinguishes it.
    """
    lines = [f"# {video.get('videoTitle') or video.get('videoId')}", ""]

    description = (video.get("description") or "").strip()
    if description:
        lines += ["## Video description", "", description, ""]

    for block in blocks(deduped):
        lines += [f"## [{timestamp(block['start'])}]", "", block["text"], ""]
    return "\n".join(lines).rstrip() + "\n"


def sidecar_meta(video: dict, deduped: list[dict]) -> dict:
    """The inbox sidecar. Everything K07 needs to open the envelope."""
    kept = [p for p in deduped if p["text"]]
    return {
        "source_kind": "YOUTUBE_VIDEO",
        "source_title": video.get("videoTitle"),
        "source_url": canonical_url(video["videoId"]),
        "source_date": (video.get("publishDate") or "")[:10] or None,
        "external_ref": video["videoId"],
        "personal_note": (
            f"Discovered by YOUTUBE via {PROVIDER}. Transcript de-overlapped "
            f"from {len(deduped)} rolling caption(s)."),
        "topics": [k for k in (video.get("keywords") or []) if k][:20],
        # Migration 030. NULL would mean "not a transcript"; this is one.
        "transcript_is_auto_generated": bool(video.get("isAutoGenerated")),
        "transcript_language": (video.get("selectedLanguage")
                                or video.get("language")),
        "transcript_provider": PROVIDER,
        "creator_external_id": video.get("channelId"),
        "creator_name": video.get("channelName"),
        "creator_external_source": "YOUTUBE",
        # Kept for the record, never for reasoning: an engine must not
        # weigh a claim by how many people watched it.
        "platform_metrics": {
            k: video.get(k) for k in
            ("viewCount", "likeCount", "commentCount", "subscriberCount",
             "durationSeconds", "segmentCount") if video.get(k) is not None},
        "segments_in": len(deduped),
        "segments_kept": len(kept),
        "words_dropped_as_overlap": sum(p["dropped_words"] for p in deduped),
    }


# ---------------------------------------------------------------------
# The call
# ---------------------------------------------------------------------

def token() -> str:
    value = (os.environ.get("APIFY_TOKEN") or "").strip()
    if not value:
        raise ApifyUnavailable(
            "APIFY_TOKEN is not set. The YOUTUBE adapter's authorization IS "
            "the Apify credential; without it there is no authorization and "
            "nothing should be requested.")
    return value


def request_body(urls: list[str]) -> bytes:
    items = [{"url": u} for u in urls] if INPUT_ITEMS_AS_OBJECTS else list(urls)
    return json.dumps({INPUT_FIELD: items}).encode("utf-8")


def parse_dataset(body: bytes) -> list[dict]:
    payload = json.loads(body.decode("utf-8"))
    if isinstance(payload, dict):
        payload = payload.get("items", payload.get("data", []))
    if not isinstance(payload, list):
        raise ApifyUnavailable(
            "the actor run did not return a dataset array. Nothing is "
            "inferred from an unexpected shape.")
    return [item for item in payload if isinstance(item, dict)]


def run_actor(conn, urls: list[str], *, transport=None) -> list[dict]:
    """One actor run for a BATCH of urls, through the chokepoint.

    The credential goes in a header, never in the query string: `fetch()`
    records the URL in `source_fetches` permanently, and a token written
    there is a token leaked to everyone with database access. `redact()`
    is the backstop, this is the practice.
    """
    if not urls:
        return []
    endpoint = RUN_URL.format(actor=ACTOR_ID)

    # A missing token is the SAME FINDING as a missing authorization note:
    # we cannot read this video. It is a refusal, recorded like every other
    # refusal (a layer that logged refusals nowhere would look exactly like
    # one that was quietly scraping), and it reaches the caller as
    # `AQ.Refused` so the item becomes ACCESS_DENIED rather than the run
    # dying on a configuration error.
    try:
        bearer = token()
    except ApifyUnavailable as exc:
        AQ.record(conn, ADAPTER, endpoint, "REFUSED_NO_CREDENTIAL",
                  detail=str(exc))
        raise AQ.Refused(str(exc)) from exc

    reply = AQ.fetch(
        conn, ADAPTER, endpoint,
        method="POST", body=request_body(urls),
        accept="application/json",
        extra_headers={"Authorization": f"Bearer {bearer}",
                       "Content-Type": "application/json"},
        transport=transport)
    return parse_dataset(reply.body)


def prepare(item: dict) -> dict:
    """One dataset item -> the document, the sidecar and the identity.

    Raises `NoTranscript` when there is nothing to preserve. That is the
    only outcome for a video without captions, and it stays true whatever
    shape such a payload turns out to have.
    """
    video_id = (item.get("videoId") or "").strip() \
        or (video_id_of(item.get("videoUrl") or "") or "")
    if not VIDEO_ID.match(video_id):
        raise NoTranscript(
            "the dataset item carries no usable videoId, so it has no stable "
            "identity and would be re-registered on every run.")
    item = {**item, "videoId": video_id}

    segments = item.get("segments")
    if not isinstance(segments, list) or not segments:
        raise NoTranscript(
            "no transcript segments were returned. There is no flat "
            "transcript field to fall back on, and an empty string must "
            "never travel as a transcript (K05/K06).")

    deduped = dedupe_segments(segments)
    document = transcript_markdown(item, deduped)
    if not any(p["text"] for p in deduped):
        raise NoTranscript(
            "every segment was empty once de-overlapped, so there is no "
            "transcript text.")
    return {"video_id": video_id, "video": item, "deduped": deduped,
            "markdown": document, "meta": sidecar_meta(item, deduped)}


def main() -> int:
    ap = argparse.ArgumentParser(description="K06 YouTube transcript (Apify)")
    ap.add_argument("--url", action="append", default=[],
                    help="video URL or id; repeat to BATCH (the start fee "
                         "dominates a single-video run)")
    ap.add_argument("--show", action="store_true",
                    help="print the rendered markdown rather than a summary")
    args = ap.parse_args()

    import psycopg
    conn = psycopg.connect(AQ.os.environ["DATABASE_URL"], autocommit=True)
    urls = [canonical_url(video_id_of(u) or u) for u in args.url]
    for item in run_actor(conn, urls):
        try:
            ready = prepare(item)
        except NoTranscript as exc:
            print(f"  FULL_TEXT_NOT_AVAILABLE  {item.get('videoId')}: {exc}")
            continue
        meta = ready["meta"]
        print(f"  {ready['video_id']}  {meta['source_title']}")
        print(f"    {meta['segments_in']} segment(s), "
              f"{meta['words_dropped_as_overlap']} overlap word(s) dropped, "
              f"auto_generated={meta['transcript_is_auto_generated']}")
        if args.show:
            print(ready["markdown"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
